# Generated by Django 4.2.3 on 2023-08-21 18:29

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                error_messages={
                    "invalid": [news.validators.validate_counter_words]
                },
                max_length=200,
            ),
        ),
    ]
