# Generated by Django 4.2.3 on 2023-08-21 21:23

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(validators=[news.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
